# Fill these in from `terraform output` after `terraform apply`.
# 52.66.199.118  = value of web_server_public_ip
# 10.0.2.33  = value of db_server_private_ip

[web]
52.66.199.118 ansible_user=ubuntu

[db]
10.0.2.33 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i ~/.ssh/travelmemory-key.pem ubuntu@52.66.199.118"'

[web:vars]
ansible_python_interpreter=/usr/bin/python3

[db:vars]
ansible_python_interpreter=/usr/bin/python3

[travelmemory:children]
web
db
